version: "2.2"
networks:
  sandbox:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    volumes:
      - ./data/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/etc/prometheus/tmp"
      - "--web.enable-lifecycle"
    restart: always
    ports:
      - 9090:9090
    networks:
      - sandbox

  alertmanger:
    image: prom/alertmanager:v0.22.0
    container_name: alertmanager
    volumes:
      - ./data/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/etc/alertmanager/tmp'
      - '--log.level=info'
    restart: always
    ports:
      - 9093:9093
      - 9094:9094
    networks:
      - sandbox

  prombox:
    image: prombox
    container_name: prombox
    restart: unless-stopped
    environment:
      - PROMETHEUS_ADDRESS=http://prometheus:9090
      - PROMETHEUS_FRAME_ADDRESS=http://localhost:9090
      - PROMETHEUS_CONFIG=/etc/data/prometheus/prometheus.yml
    ports:
      - 3000:3000
    networks:
      - sandbox
    volumes:
      - ./data:/etc/data:rw
