global:
  scrape_interval: 10m
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    client: elements
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
